name: Build tg_cpphost

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up dependencies
        run: |
          ./scripts/deps.sh

      - name: Clang (Perf)
        env:
          CC: clang
          CXX: clang++
        run: |
          mkdir -p build
          cd build
          ../scripts/perf.sh

      - name: GCC (Debug)
        env:
          CC: gcc
          CXX: g++
        run: |
          mkdir -p build
          cd build
          ../scripts/debug.sh
