name: Build tg_cpphost

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install clang gcc libcurl4-openssl-dev libboost-all-dev cmake
          git submodule init
          git submodule update

      - name: Build and test with clang
        env:
          CC: clang
          CXX: clang++
        run: |
          mkdir -p build
          cd build
          cmake ..
          make

      - name: Build and test with gcc
        env:
          CC: gcc
          CXX: g++
        run: |
          mkdir -p build
          cd build
          cmake ..
          make
